<%@ Page Title="" Language="C#" MasterPageFile="~/App_Master/SellerMaster.master" AutoEventWireup="true" CodeBehind="Seller.aspx.cs" Inherits="SSManagment.Seller" %>

<asp:Content ID="cntCategories" ContentPlaceHolderID="cphStandartCategories" runat="server">
	<table cellpadding="0" cellspacing="0">
		<tr>
			<td>
				<div class="Widget_heading_container"><span class="Widget_heading_container_Span"></span>
					<h2>
						Разделы</h2>
				</div>
				<div class="Widget_Body_container">
					<div class="Widget_Body_top"><span></span></div>
					<div class="Widget_Body_content">
						<div class="clear"></div>
						<div style="overflow: auto; width: 200px; background-color: #F7F7DE;">
							<asp:UpdatePanel ID="uplTree" runat="server" UpdateMode="Conditional">
								<ContentTemplate>
									<asp:TreeView ID="treeCategories" runat="server" ExpandDepth="1" AutoGenerateDataBindings="true" ForeColor="#333333" ShowLines="True" Height="100%" Width="200px" BackColor="#F7F7DE" OnSelectedNodeChanged="treeCategories_SelectedNodeChanged" Font-Size="8pt" SelectedNodeStyle-BorderColor="#CC3300" SelectedNodeStyle-BorderWidth="3" SelectedNodeStyle-BorderStyle="Double">
										<ParentNodeStyle ForeColor="White" BackColor="#6B696B" BorderColor="#CCCCCC" BorderStyle="Dashed" BorderWidth="1px" Font-Bold="True" NodeSpacing="1px" />
										<RootNodeStyle ForeColor="White" BackColor="#6B696B" BorderColor="#CCCCCC" BorderWidth="1px" Font-Bold="True" NodeSpacing="1px" />
									</asp:TreeView>
								</ContentTemplate>
								<Triggers>
									<asp:AsyncPostBackTrigger ControlID="treeCategories" EventName="DataBinding" />
								</Triggers>
							</asp:UpdatePanel>
						</div>
						<div class="clear"></div>
					</div>
				</div>
				<div class="Widget_Body_bottom"><span></span></div>
			</td>
		</tr>
	</table>
</asp:Content>
<asp:Content ID="cntProducts" ContentPlaceHolderID="cphStandartProducts" runat="server">
	<asp:UpdatePanel ID="uplProductsGrid" runat="server" UpdateMode="Always">
		<ContentTemplate>
			<div class="Widget_heading_container"><span class="Widget_heading_container_Span"></span>
				<h2>
					Товары из раздела : &nbsp;<asp:Label ID="lblCurrentCategori" runat="server"></asp:Label></h2>
			</div>
			<div class="Widget_Body_container">
				<div class="Widget_Body_top"><span></span></div>
				<div class="Widget_Body_content">
					<div class="clear"></div>
					<table cellpadding="0" cellspacing="0" width="100%">
						<tr>
							<td align="center">
								<table>
									<tr>
										<td align="right">
											<asp:TextBox ID="txtFind" runat="server" Width="200px"></asp:TextBox>
										</td>
										<td>
											<button id="btnFind" runat="server" onserverclick="btnFind_Click">
												<span><em>Найти</em></span></button>
										</td>
									</tr>
								</table>
							</td>
						</tr>
						<tr>
							<td>
								<asp:GridView ID="gvwProducts" runat="server" Width="100%" AutoGenerateColumns="False" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" CaptionAlign="Top" CellPadding="0" ForeColor="Black" GridLines="Vertical" OnRowCommand="gvwProducts_RowCommand" Font-Size="8pt" AllowSorting="True" OnRowCreated="gvwProducts_RowCreated" OnSorting="gvwProducts_Sorting" PagerStyle-Wrap="False" DataKeyNames="id" OnRowDataBound="gvwProducts_RowDataBound">
									<RowStyle BackColor="#F7F7DE" />
									<Columns>
										<asp:TemplateField HeaderText="id" Visible="False">
											<ItemTemplate>
												<asp:Label ID="lblID" runat="server" Text='<%# Bind("id") %>'></asp:Label>
											</ItemTemplate>
										</asp:TemplateField>
										<asp:BoundField DataField="name" SortExpression="name" HeaderText="Название" ReadOnly="True" HeaderStyle-Wrap="False">
											<HeaderStyle Wrap="False" />
										</asp:BoundField>
										<asp:TemplateField ItemStyle-HorizontalAlign="Center" ItemStyle-VerticalAlign="Middle">
											<ItemTemplate>
												<asp:LinkButton ID="lbtnOrder" runat="server" CommandName="order" CausesValidation="false" CommandArgument='<%# Eval("id") %>'>
													<asp:Image ID="img" runat="server" ImageUrl="~/App_Themes/Main/Icons/16px-Dialog-information_on.svg.png" Width="16px" Height="16px" /></asp:LinkButton>
											</ItemTemplate>
										</asp:TemplateField>
										<asp:TemplateField HeaderText="В наличии" SortExpression="count" ItemStyle-Wrap="false" ItemStyle-HorizontalAlign="Right" ItemStyle-VerticalAlign="Middle">
											<ItemTemplate>
												<asp:Label ID="lblCount" runat="server" Text='<%# Bind("count") %>' ForeColor="Black"></asp:Label>
												<span id="spanCountCalc" runat="server" visible="false">-
													<asp:Button ID="btnUnReserv" runat="server" Text='<%# Bind("reserveCount") %>' CommandName="unreserv" CausesValidation="false" CommandArgument='<%# Eval("id") %>' Height="18px" Font-Size="8pt" />
													= <span id="spanSum" runat="server" style="color: #33CC33; font-size: 9pt; font-weight: bold; font-style: normal; font-variant: normal"></span></span></ItemTemplate>
											<HeaderStyle Wrap="False" />
											<ItemStyle Wrap="False" />
										</asp:TemplateField>
										<asp:BoundField DataField="measure" SortExpression="measure" HeaderText="Изм." NullDisplayText="шт" ItemStyle-HorizontalAlign="Center" HeaderStyle-Wrap="False">
											<ControlStyle Width="10px" />
											<HeaderStyle Wrap="False" />
											<ItemStyle HorizontalAlign="Center" />
										</asp:BoundField>
										<asp:BoundField DataField="bprice" DataFormatString="{0}р." SortExpression="bprice" HeaderText="Цена" NullDisplayText="уточнить" ItemStyle-HorizontalAlign="Right" HeaderStyle-Wrap="False">
											<ControlStyle Width="50px" />
											<HeaderStyle Wrap="False" />
											<ItemStyle HorizontalAlign="Right" />
										</asp:BoundField>
										<asp:TemplateField ShowHeader="False" ItemStyle-HorizontalAlign="Center" ItemStyle-VerticalAlign="Middle">
											<ItemTemplate>
												<asp:ImageButton ID="ibtnAdd" runat="server" CausesValidation="false" CommandName="add" ToolTip="Добаваить в корзину" ImageUrl="~/App_Themes/Main/Icons/16px-Ambox_emblem_plus.svg.png" CommandArgument='<%# Eval("id") %>' />
											</ItemTemplate>
											<ControlStyle Height="16px" Width="16px" />
										</asp:TemplateField>
										<asp:TemplateField ShowHeader="False" ItemStyle-HorizontalAlign="Center" ItemStyle-VerticalAlign="Middle" Visible="false">
											<ItemTemplate>
												<asp:ImageButton ID="ibtnSale" runat="server" CausesValidation="false" CommandName="sale" CommandArgument='<%# Eval("id") %>' ImageUrl="~/App_Themes/Main/Icons/16px-Emblem-advertisement-dollar.svg.png" ToolTip="Продать" />
											</ItemTemplate>
											<ControlStyle Height="16px" Width="16px" />
										</asp:TemplateField>
										<asp:TemplateField ShowHeader="False" ItemStyle-HorizontalAlign="Center" ItemStyle-VerticalAlign="Middle">
											<ItemTemplate>
												<asp:ImageButton ID="ibtnReserv" runat="server" CausesValidation="false" CommandName="reserved" CommandArgument='<%# Eval("id") %>' ImageUrl="~/App_Themes/Main/Icons/16px-Emblem-symbolic-link.svg.png" ToolTip="Зарезервировать" />
											</ItemTemplate>
											<ControlStyle Height="16px" Width="16px" />
										</asp:TemplateField>
									</Columns>
									<EmptyDataTemplate>
										<center>
											<span>В выбраном вами разделе продуктов ненайдено!</span></center>
									</EmptyDataTemplate>
									<FooterStyle BackColor="#CCCC99" />
									<PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
									<SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
									<HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" Wrap="False" />
									<AlternatingRowStyle BackColor="White" />
								</asp:GridView>
								&nbsp;
							</td>
						</tr>
					</table>
					<div class="clear"></div>
				</div>
			</div>
			<div class="Widget_Body_bottom"><span></span></div>
		</ContentTemplate>
	</asp:UpdatePanel>
</asp:Content>
<asp:Content ID="cntBuy" ContentPlaceHolderID="cphStandartBuy" runat="server">
	<asp:UpdatePanel ID="uplShoppingCart" runat="server">
		<ContentTemplate>
			<table cellpadding="0" cellspacing="0">
				<tr>
					<td>
						<div class="Widget_heading_container"><span class="Widget_heading_container_Span"></span>
							<h2>
								Список покупок ( корзина)</h2>
						</div>
						<div class="Widget_Body_container">
							<div class="Widget_Body_top"><span></span></div>
							<div class="Widget_Body_content">
								<div class="clear"></div>
								<table cellpadding="0" cellspacing="0" width="100%" style="margin-left: -3px">
									<tr>
										<td>
											<button id="btn_ClearByeList" runat="server" style="width: 100%" onserverclick="btn_ClearByeList_Click">
												<span><em>Очистить</em></span></button>
										</td>
									</tr>
									<tr>
										<td align="center">
											<asp:GridView ID="gvwShoppingCart" runat="server" Width="100%" AutoGenerateColumns="False" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" CellPadding="2" ForeColor="Black" GridLines="Vertical" OnRowCommand="gvwShoppingCart_RowCommand" OnRowDeleting="gvwShoppingCart_RowDeleting" Font-Size="7pt">
												<RowStyle BackColor="#F7F7DE" />
												<Columns>
													<asp:TemplateField HeaderText="id" Visible="False">
														<ItemTemplate>
															<asp:Label ID="lblID" runat="server" Text='<%# Bind("id") %>'></asp:Label>
														</ItemTemplate>
													</asp:TemplateField>
													<asp:BoundField HeaderText="Товар" DataField="name"></asp:BoundField>
													<asp:BoundField HeaderText="Цена" DataField="bprice" DataFormatString="{0}р." NullDisplayText="уточнить" ItemStyle-HorizontalAlign="Right"></asp:BoundField>
													<asp:TemplateField HeaderText="Кол-во">
														<ItemTemplate>
															<asp:TextBox ID="txtBuyCount" OnTextChanged="txtBuyCount_TextChanged" runat="server" Text='<%# Eval("BuyCount") %>' Width="20px" AutoPostBack="True"></asp:TextBox>
														</ItemTemplate>
														<ControlStyle Width="27px" />
													</asp:TemplateField>
													<asp:BoundField HeaderText="Итого" DataField="ResultPrice" DataFormatString="{0}р." NullDisplayText="0" ItemStyle-HorizontalAlign="Right"></asp:BoundField>
													<asp:TemplateField ShowHeader="False">
														<ItemTemplate>
															<asp:ImageButton ID="btnDelete" runat="server" CausesValidation="false" CommandName="delete" CommandArgument='<%# Eval("id") %>' ImageUrl="~/App_Themes/Main/Icons/24px-Dialog-error.svg.png" ToolTip="Удалить" />
														</ItemTemplate>
														<ControlStyle Height="24px" Width="24px" />
													</asp:TemplateField>
												</Columns>
												<EmptyDataTemplate>
													<center>
														<span>Список покупок пуст</span></center>
												</EmptyDataTemplate>
												<FooterStyle BackColor="#CCCC99" />
												<PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
												<SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
												<HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
												<AlternatingRowStyle BackColor="White" />
											</asp:GridView>
										</td>
									</tr>
									<tr>
										<td>
											<table>
												<tr>
													<td align="left" style="width: 90px">
														<span>Покупатель :</span>
													</td>
													<td align="left">
														<asp:DropDownList ID="drpBuyer" runat="server" OnSelectedIndexChanged="drpBuyer_SelectedIndexChanged" Width="120px" AutoPostBack="True">
														</asp:DropDownList>
													</td>
												</tr>
											</table>
										</td>
									</tr>
									<tr>
										<td>
											&nbsp; <span id="spanShopingCartSum" runat="server" visible="false">Итого :&nbsp;</span><asp:Label ID="lblSum" runat="server"></asp:Label>
										</td>
									</tr>
									<tr>
										<td>
											<button id="btnBuy" runat="server" style="width: 100%" onserverclick="btnBuy_Click">
												<span><em>Оформить покупку</em></span></button>
										</td>
									</tr>
								</table>
								<div class="clear"></div>
							</div>
						</div>
						<div class="Widget_Body_bottom"><span></span></div>
					</td>
				</tr>
				<tr>
					<td>
						<div class="Widget_heading_container"><span class="Widget_heading_container_Span"></span>
							<h2>
								Дополнительно</h2>
						</div>
						<div class="Widget_Body_container">
							<div class="Widget_Body_top"><span></span></div>
							<div class="Widget_Body_content">
								<div class="clear"></div>
								<center>
									<button id="btnAdmin" runat="server" style="width: 180px" onserverclick="btnAdminClick">
										<span><em>Администрирование</em></span></button>
									<br />
									<button id="btnReturn" runat="server" style="width: 180px" onserverclick="btnReturn_Click">
										<span><em>Возврат товара</em></span></button>
									<br />
									<button id="btnDemand" runat="server" style="width: 180px" onserverclick="btnDemand_Click">
										<span><em>Спрос на товар</em></span></button>
								</center>
								<div class="clear"></div>
							</div>
						</div>
						<div class="Widget_Body_bottom"><span></span></div>
					</td>
				</tr>
			</table>
		</ContentTemplate>
	</asp:UpdatePanel>
</asp:Content>
<asp:Content ID="cntFooter" ContentPlaceHolderID="StandartFooter" runat="server">
	<asp:UpdatePanel ID="uplFooter" runat="server" UpdateMode="Always">
		<ContentTemplate>
			<div id="modalBuyConfirm" runat="server" visible="false">
				<div class="overlay"></div>
				<div class="content">
					<center>
						<div>
							<div class="Widget_heading_container"><span class="Widget_heading_container_Span"></span>
								<center>
									<h2>
										Оформить покупки? </h2>
								</center>
							</div>
							<div class="Widget_Body_container">
								<div class="Widget_Body_top"><span></span></div>
								<div class="Widget_Body_content">
									<div class="clear"></div>
									<center>
										<table cellpadding="0" cellspacing="0">
											<tr>
												<td align="center" colspan="3">
													<asp:GridView ID="gvwShpingCartConfirm" runat="server" Width="100%" AutoGenerateColumns="False" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" CellPadding="2" ForeColor="Black" GridLines="Vertical" Font-Size="9pt">
														<RowStyle BackColor="#F7F7DE" />
														<Columns>
															<asp:BoundField HeaderText="Товар" DataField="name">
																<ControlStyle Width="100%" />
																<ItemStyle HorizontalAlign="Left" />
															</asp:BoundField>
															<asp:BoundField HeaderText="Цена" DataFormatString="{0}р." DataField="bprice" NullDisplayText="уточнить" ItemStyle-HorizontalAlign="Right">
																<ControlStyle Width="50px" />
																<ItemStyle HorizontalAlign="Right" />
															</asp:BoundField>
															<asp:BoundField HeaderText="Кол-во" DataField="BuyCount" NullDisplayText="0" ItemStyle-HorizontalAlign="Right">
																<ControlStyle Width="50px" />
																<ItemStyle HorizontalAlign="Right" />
															</asp:BoundField>
															<asp:BoundField HeaderText="Итого" DataFormatString="{0}р." DataField="ResultPrice" NullDisplayText="0" ItemStyle-HorizontalAlign="Right">
																<ControlStyle Width="50px" />
																<ItemStyle HorizontalAlign="Right" />
															</asp:BoundField>
														</Columns>
														<EmptyDataTemplate>
															<center>
																<span>Список покупок пуст</span></center>
														</EmptyDataTemplate>
														<FooterStyle BackColor="#CCCC99" />
														<PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
														<SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
														<HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
														<AlternatingRowStyle BackColor="White" />
													</asp:GridView>
													<br />
												</td>
											</tr>
											<tr>
												<td>
													<asp:DropDownList ID="drpShopConfirmBuyer" runat="server" OnSelectedIndexChanged="drpShopConfirmBuyer_SelectedIndexChanged" Width="120px" AutoPostBack="True">
													</asp:DropDownList>
												</td>
												<td>
													<span id="spanShopConfirm" runat="server">Итого :&nbsp;</span><asp:Label ID="lblShopConfirmSum" runat="server" Font-Size="12pt"></asp:Label>
												</td>
												<td>
													<asp:CheckBox ID="cbxCreditShopConfirm" runat="server" Checked="false" Text="В кредит" />
												</td>
											</tr>
											<tr>
												<td colspan="3">
													<asp:CheckBox ID="chkViewReportShopConfirm" runat="server" Text="Показать отчет по продаже" />
												</td>
											</tr>
											<tr>
												<td colspan="3">
													<br />
												</td>
											</tr>
											<tr>
												<td>
													<button id="btnYes" runat="server" style="width: 75px;" onserverclick="btnYes_Click">
														<span><em>Да</em></span></button>
												</td>
												<td>
												</td>
												<td>
													<button id="btnCancel" runat="server" style="width: 75px;" onserverclick="btnCancel_Click">
														<span><em>Нет</em></span></button>
												</td>
											</tr>
										</table>
									</center>
									<div class="clear"></div>
								</div>
							</div>
							<div class="Widget_Body_bottom"><span></span></div>
						</div>
					</center>
				</div>
			</div>
			<div id="modalSingleBuy" runat="server" visible="false">
				<div class="overlay"></div>
				<div class="content">
					<center>
						<div>
							<div class="Widget_heading_container"><span class="Widget_heading_container_Span"></span>
								<center>
									<h2>
										Оформить покупку? </h2>
								</center>
							</div>
							<div class="Widget_Body_container">
								<div class="Widget_Body_top"><span></span></div>
								<div class="Widget_Body_content">
									<div class="clear"></div>
									<center>
										<table cellpadding="0" cellspacing="0" width="100%">
											<tr>
												<td align="center" colspan="3">
													<asp:GridView ID="gvwSingleBuy" runat="server" Width="100%" AutoGenerateColumns="False" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" CellPadding="2" ForeColor="Black" GridLines="Vertical" Font-Size="9pt">
														<RowStyle BackColor="#F7F7DE" />
														<Columns>
															<asp:TemplateField HeaderText="id" Visible="False">
																<ItemTemplate>
																	<asp:Label ID="lblID" runat="server" Text='<%# Bind("id") %>'></asp:Label>
																</ItemTemplate>
															</asp:TemplateField>
															<asp:BoundField HeaderText="Товар" DataField="name">
																<ItemStyle HorizontalAlign="Left" />
															</asp:BoundField>
															<asp:BoundField HeaderText="Цена" DataFormatString="{0}р." DataField="bprice" NullDisplayText="уточнить" ItemStyle-HorizontalAlign="Right">
																<ControlStyle Width="50px" />
																<ItemStyle HorizontalAlign="Right" />
															</asp:BoundField>
															<asp:TemplateField HeaderText="Кол-во">
																<ItemTemplate>
																	<asp:TextBox ID="txtSingleBuyCount" OnTextChanged="txtSingleBuyCount_TextChanged" runat="server" Text='<%# Eval("BuyCount") %>' Width="20px" AutoPostBack="True"></asp:TextBox>
																</ItemTemplate>
																<ControlStyle Width="27px" />
															</asp:TemplateField>
														</Columns>
														<EmptyDataTemplate>
															<center>
																<span>Список покупок пуст</span></center>
														</EmptyDataTemplate>
														<FooterStyle BackColor="#CCCC99" />
														<PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
														<SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
														<HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
														<AlternatingRowStyle BackColor="White" />
													</asp:GridView>
												</td>
											</tr>
											<tr>
												<td>
													<asp:DropDownList ID="drpSingleBuyBuyerList" runat="server" OnSelectedIndexChanged="drpSingleBuyBuyerList_SelectedIndexChanged" Width="120px" AutoPostBack="True">
													</asp:DropDownList>
												</td>
												<td>
													<span id="spanSingleBuySum" runat="server">Итого :&nbsp;</span><asp:Label ID="lblSingleBuySum" runat="server" Font-Size="12pt"></asp:Label>
												</td>
												<td>
													<asp:CheckBox ID="cbxCreditSingleBuy" runat="server" Checked="false" Text="В кредит" />
												</td>
											</tr>
											<tr>
												<td colspan="3">
													<asp:CheckBox ID="chkViewReportSingleBuy" runat="server" Text="Показать отчет по продаже" />
												</td>
											</tr>
											<tr>
												<td colspan="3">
													<br />
												</td>
											</tr>
											<tr>
												<td>
												</td>
												<td>
													<button id="btnSingleBuyYes" runat="server" style="width: 75px;" onserverclick="btnSingleBuyYes_Click">
														<span><em>Да</em></span></button>
												</td>
												<td>
													<button id="btnSingleBuyNo" runat="server" style="width: 75px;" onserverclick="btnSingleBuyNo_Click">
														<span><em>Нет</em></span></button>
												</td>
											</tr>
										</table>
									</center>
									<div class="clear"></div>
								</div>
							</div>
							<div class="Widget_Body_bottom"><span></span></div>
						</div>
					</center>
				</div>
			</div>
			<div id="modalUnReservConfirm" runat="server" visible="false">
				<div class="overlay"></div>
				<div class="content">
					<center>
						<div>
							<div class="Widget_heading_container"><span class="Widget_heading_container_Span"></span>
								<center>
									<h2>
										Вернуть в продажу зарезервироанный товар? </h2>
								</center>
							</div>
							<div class="Widget_Body_container">
								<div class="Widget_Body_top"><span></span></div>
								<div class="Widget_Body_content">
									<div class="clear"></div>
									<center>
										<table>
											<tr>
												<td>
													<asp:HiddenField ID="hdnUnReservId" runat="server" />
													<button id="btnUnReservYes" runat="server" style="width: 75px;" onserverclick="btnUnReservYes_Click">
														<span><em>Да</em></span></button>
												</td>
												<td>
													<button id="btnUnReservNo" runat="server" style="width: 75px;" onserverclick="btnUnReservNo_Click">
														<span><em>Нет</em></span></button>
												</td>
											</tr>
										</table>
									</center>
									<div class="clear"></div>
								</div>
							</div>
							<div class="Widget_Body_bottom"><span></span></div>
						</div>
					</center>
				</div>
			</div>
			<div id="modalWarningConfirm" runat="server" visible="false">
				<div class="overlay"></div>
				<div class="content">
					<center>
						<div>
							<div class="Widget_heading_container"><span class="Widget_heading_container_Span"></span>
								<center>
									<h2 style="color: #FF6600; font-weight: bold">
										Внимание !!! </h2>
								</center>
							</div>
							<div class="Widget_Body_container">
								<div class="Widget_Body_top"><span></span></div>
								<div class="Widget_Body_content">
									<div class="clear"></div>
									<center>
										<table width="100%">
											<tr>
												<td>
													<asp:Label ID="lblWarning" runat="server"></asp:Label>
													<br />
													<br />
												</td>
											</tr>
											<tr>
												<td>
													Попробуйте позже и известите администратора об этом сообщении, а также укажите ситуацию при которой это сообщение появляется.
												</td>
											</tr>
											<tr>
												<td>
													<br />
													<button id="btnWarningOk" runat="server" style="width: 75px;" onserverclick="btnWarningOk_Click">
														<span><em>Да</em></span></button>
												</td>
											</tr>
										</table>
									</center>
									<div class="clear"></div>
								</div>
							</div>
							<div class="Widget_Body_bottom"><span></span></div>
						</div>
					</center>
				</div>
			</div>
			<div id="modalDemand" runat="server" visible="false">
				<div class="overlay"></div>
				<div class="content">
					<center>
						<div>
							<div class="Widget_heading_container"><span class="Widget_heading_container_Span"></span>
								<center>
									<h2>
										Оформить спрос на товар который не представлен в ассортименте.</h2>
								</center>
							</div>
							<div class="Widget_Body_container">
								<div class="Widget_Body_top"><span></span></div>
								<div class="Widget_Body_content">
									<div class="clear"></div>
									<center>
										<table width="100%">
											<tr>
												<td align="center" colspan="2">
													<span>Название товара :&nbsp;</span><asp:TextBox ID="txtDemandProduct" runat="server" Width="250px"></asp:TextBox>
													<br />
													<br />
												</td>
											</tr>
											<tr>
												<td>
													<button id="btnDemandOk" runat="server" style="width: 75px;" onserverclick="btnDemandOk_Click">
														<span><em>Да</em></span></button>
												</td>
												<td>
													<button id="btnDemandNo" runat="server" style="width: 75px;" onserverclick="btnDemandNo_Click">
														<span><em>Нет</em></span></button>
												</td>
											</tr>
										</table>
									</center>
									<div class="clear"></div>
								</div>
							</div>
							<div class="Widget_Body_bottom"><span></span></div>
						</div>
					</center>
				</div>
			</div>
			<div id="modalReturn" runat="server" visible="false">
				<div class="overlay"></div>
				<div class="content">
					<center>
						<div style="width: 500px;">
							<div class="Widget_heading_container"><span class="Widget_heading_container_Span"></span>
								<center>
									<h2>
										Возврат товара </h2>
								</center>
							</div>
							<div class="Widget_Body_container">
								<div class="Widget_Body_top"><span></span></div>
								<div class="Widget_Body_content">
									<div class="clear"></div>
									<center>
										<table width="100%">
											<tr>
												<td>
													<br />
													<button id="Button1" runat="server" style="width: 75px;" onserverclick="btnReturnOk_Click">
														<span><em>Закрыть</em></span></button>
												</td>
											</tr>
											<tr>
												<td align="center">
													<table cellpadding="0" cellspacing="0" width="100%">
														<tr>
															<td align="right">
																Введите код листа товаров:&nbsp;
															</td>
															<td align="left">
																<asp:TextBox ID="txtReturnProductCode" runat="server" Width="150px"></asp:TextBox>
															</td>
														</tr>
														<tr>
															<td align="right">
																Введите дату покупки:&nbsp;
															</td>
															<td align="left">
																<table cellpadding="0" cellspacing="0" width="200px">
																	<tr>
																		<td valign="middle">
																			<asp:TextBox ID="txtReturnProductSoldDate" runat="server" Width="150px"></asp:TextBox>
																		</td>
																		<td valign="middle">
																			<asp:ImageButton ID="ibtnShowCalendar" runat="server" OnClick="ibtnShowCalendar_Click" ImageUrl="~/App_Themes/Main/Icons/Calendar48.png" />
																		</td>
																	</tr>
																	<tr>
																		<td valign="top" colspan="2">
																			<asp:Calendar ID="calReturnProductSoldDate" runat="server" Visible="false" BackColor="White" BorderColor="#999999" CellPadding="4" DayNameFormat="Shortest" Font-Names="Verdana" Font-Size="8pt" ForeColor="Black" Height="180px" Width="200px" OnSelectionChanged="calReturnProductSoldDate_SelectionChanged">
																				<SelectedDayStyle BackColor="#666666" Font-Bold="True" ForeColor="White" />
																				<SelectorStyle BackColor="#CCCCCC" />
																				<WeekendDayStyle BackColor="#FFFFCC" />
																				<TodayDayStyle BackColor="#CCCCCC" ForeColor="Black" />
																				<OtherMonthDayStyle ForeColor="#808080" />
																				<NextPrevStyle VerticalAlign="Bottom" />
																				<DayHeaderStyle BackColor="#CCCCCC" Font-Bold="True" Font-Size="7pt" />
																				<TitleStyle BackColor="#999999" BorderColor="Black" Font-Bold="True" />
																			</asp:Calendar>
																		</td>
																	</tr>
																</table>
															</td>
														</tr>
														<tr>
															<td colspan="2" align="center">
																<br />
																<button id="btnReturnShowProducts" runat="server" style="width: 185px;" onserverclick="btnReturnShowProducts_Click">
																	<span><em>Показать список товаров</em></span></button>
															</td>
														</tr>
													</table>
												</td>
											</tr>
											<tr>
												<td align="center">
													<div style="overflow: auto; height: 500px; width: 100%; position: relative;">
														<asp:GridView ID="gvwReturn" runat="server" Width="95%" AutoGenerateColumns="False" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" CellPadding="2" ForeColor="Black" GridLines="Vertical" Font-Size="9pt" OnRowDataBound="gvwReturn_RowDataBound" OnRowCommand="gvwReturn_RowCommand" OnRowDeleting="gvwReturn_RowDeleting">
															<RowStyle BackColor="#F7F7DE" />
															<Columns>
																<asp:BoundField HeaderText="Товар" DataField="logName">
																	<ControlStyle Width="100%" />
																	<ItemStyle HorizontalAlign="Left" />
																</asp:BoundField>
																<asp:BoundField HeaderText="Покупатель" DataField="buerName">
																	<ControlStyle Width="50px" />
																	<ItemStyle HorizontalAlign="Right" />
																</asp:BoundField>
																<asp:BoundField HeaderText="Дата продажи" DataField="date" ItemStyle-HorizontalAlign="Right">
																	<ItemStyle HorizontalAlign="Right" />
																</asp:BoundField>
																<asp:BoundField HeaderText="Цена" DataFormatString="{0}р." DataField="logBprice" NullDisplayText="уточнить" ItemStyle-HorizontalAlign="Right">
																	<ControlStyle Width="50px" />
																	<ItemStyle HorizontalAlign="Right" />
																</asp:BoundField>
																<asp:BoundField HeaderText="Кол-во" DataField="itemsCount" NullDisplayText="0" ItemStyle-HorizontalAlign="Right">
																	<ControlStyle Width="50px" />
																	<ItemStyle HorizontalAlign="Right" />
																</asp:BoundField>
																<asp:TemplateField HeaderText="Итого" ItemStyle-HorizontalAlign="Right">
																	<ItemTemplate>
																		<asp:Label ID="lblReturnItogo" runat="server" Text='<%# Bind("cash") %>'></asp:Label><span>р.</span> </ItemTemplate>
																</asp:TemplateField>
																<asp:TemplateField ShowHeader="False">
																	<ItemTemplate>
																		<asp:TextBox ID="txtReturnCount" runat="server" Width="20px" AutoPostBack="True"></asp:TextBox>
																	</ItemTemplate>
																	<ControlStyle Width="27px" />
																</asp:TemplateField>
																<asp:TemplateField ShowHeader="False">
																	<ItemTemplate>
																		<asp:ImageButton ID="btnReturn" runat="server" CausesValidation="false" CommandName="return" CommandArgument='<%# Eval("id") %>' ImageUrl="~/App_Themes/Main/Icons/Source/48px-Ambox_emblem_arrow.svg.png" ToolTip="Вернуть" />
																	</ItemTemplate>
																	<ControlStyle Height="24px" Width="24px" />
																</asp:TemplateField>
															</Columns>
															<EmptyDataTemplate>
																<center>
																	<span>Список покупок пуст</span></center>
															</EmptyDataTemplate>
															<FooterStyle BackColor="#CCCC99" />
															<PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
															<SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
															<HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
															<AlternatingRowStyle BackColor="White" />
														</asp:GridView>
													</div>
												</td>
											</tr>
											<tr>
												<td>
													<br />
													<button id="btnReturnOk" runat="server" style="width: 75px;" onserverclick="btnReturnOk_Click">
														<span><em>Закрыть</em></span></button>
												</td>
											</tr>
										</table>
									</center>
									<div class="clear"></div>
								</div>
							</div>
							<div class="Widget_Body_bottom"><span></span></div>
						</div>
					</center>
				</div>
			</div>
			<div id="modalReturnConfirm" runat="server" visible="false">
				<div class="overlay"></div>
				<div class="content">
					<center>
						<div>
							<div class="Widget_heading_container"><span class="Widget_heading_container_Span"></span>
								<center>
									<h2>
										Вернуть товар в магазин? </h2>
								</center>
							</div>
							<div class="Widget_Body_container">
								<div class="Widget_Body_top"><span></span></div>
								<div class="Widget_Body_content">
									<div class="clear"></div>
									<center>
										<table width="100%">
											<tr>
												<td colspan="2">
													Вернуть &nbsp;<asp:Label ID="lblReturnModalCount" runat="server"></asp:Label>
													&nbsp;<asp:Label ID="lblReturnModalProductMeasure" runat="server" Text="Label"></asp:Label>
													&nbsp;<asp:Label ID="lblReturnModalProductName" runat="server"></asp:Label>
												</td>
											</tr>
											<tr>
												<td colspan="2">
													Выплата по возврату составит: &nbsp;<asp:Label ID="lbleturnModalSum" runat="server"></asp:Label>
													<br />
												</td>
											</tr>
											<tr>
												<td>
													<asp:HiddenField ID="hdnReturnID" runat="server" />
													<button id="btnReturnConfirmOk" runat="server" style="width: 75px;" onserverclick="btnReturnConfirmOk_Click">
														<span><em>Да</em></span></button>
												</td>
												<td>
													<button id="ReturnConfirmNo" runat="server" style="width: 75px;" onserverclick="ReturnConfirmNo_Click">
														<span><em>Нет</em></span></button>
												</td>
											</tr>
										</table>
									</center>
									<div class="clear"></div>
								</div>
							</div>
							<div class="Widget_Body_bottom"><span></span></div>
						</div>
					</center>
				</div>
			</div>
			<div id="modalOrderConfirm" runat="server" visible="false">
				<div class="overlay"></div>
				<div class="content">
					<center>
						<div>
							<div class="Widget_heading_container"><span class="Widget_heading_container_Span"></span>
								<center>
									<h2>
										Подать заявку на закупку товара? </h2>
								</center>
							</div>
							<div class="Widget_Body_container">
								<div class="Widget_Body_top"><span></span></div>
								<div class="Widget_Body_content">
									<div class="clear"></div>
									<center>
										<table width="100%">
											<tr>
												<td>
													<asp:HiddenField ID="hdnOrder" runat="server" />
													<button id="btnOrderYes" runat="server" style="width: 75px;" onserverclick="btnOrderYes_Click">
														<span><em>Да</em></span></button>
												</td>
												<td>
													<button id="btnOrderNo" runat="server" style="width: 75px;" onserverclick="btnOrderNo_Click">
														<span><em>Нет</em></span></button>
												</td>
											</tr>
										</table>
									</center>
									<div class="clear"></div>
								</div>
							</div>
							<div class="Widget_Body_bottom"><span></span></div>
						</div>
					</center>
				</div>
			</div>
			<div id="modalReserv" runat="server" visible="false">
				<div class="overlay"></div>
				<div class="content">
					<center>
						<div>
							<div class="Widget_heading_container"><span class="Widget_heading_container_Span"></span>
								<center>
									<h2>
										Зарезервировать товар </h2>
								</center>
							</div>
							<div class="Widget_Body_container">
								<div class="Widget_Body_top"><span></span></div>
								<div class="Widget_Body_content">
									<div class="clear"></div>
									<center>
										<table width="100%">
											<tr>
												<td colspan="2">
													<table cellpadding="0" width="100%">
														<tr>
															<td align="right">
																<span>Название товара :</span>
															</td>
															<td align="left">
																<asp:Label ID="lblResrvName" runat="server"></asp:Label>
																<asp:HiddenField ID="hdnResrvID" runat="server" />
															</td>
														</tr>
														<tr>
															<td align="right">
																<span>В наличии :</span>
															</td>
															<td align="left">
																<asp:Label ID="lblResrvCount" runat="server"></asp:Label>
															</td>
														</tr>
														<tr>
															<td align="right">
																<span>Зарезервировано :</span>
															</td>
															<td align="left">
																<asp:Label ID="lblResrvReserved" runat="server"></asp:Label>
															</td>
														</tr>
														<tr>
															<td align="right">
																<span>Цена :</span>
															</td>
															<td align="left">
																<asp:Label ID="lblResrvBprice" runat="server"></asp:Label>
															</td>
														</tr>
														<tr>
															<td align="right">
																<span>Зарезервировать :</span>
															</td>
															<td align="left">
																<asp:TextBox ID="txtResrvBuyCount" runat="server" OnTextChanged="txtResrvBuyCount_TextChanged"></asp:TextBox>
															</td>
														</tr>
														<tr>
															<td align="right">
																<span>Итого :</span>
															</td>
															<td align="left">
																<asp:Label ID="lblResrvSum" runat="server"></asp:Label>
															</td>
														</tr>
													</table>
												</td>
											</tr>
											<tr>
												<td colspan="2" align="center">
													<span>Непродавать товар до</span>
													<asp:Calendar ID="calResrvReservDateTo" runat="server" BackColor="White" BorderColor="#999999" CellPadding="4" DayNameFormat="Shortest" Font-Names="Verdana" Font-Size="8pt" ForeColor="Black" Height="180px" Width="200px" OnSelectionChanged="calResrvReservDateTo_SelectionChanged">
														<SelectedDayStyle BackColor="#666666" Font-Bold="True" ForeColor="White" />
														<SelectorStyle BackColor="#CCCCCC" />
														<WeekendDayStyle BackColor="#FFFFCC" />
														<TodayDayStyle BackColor="#CCCCCC" ForeColor="Black" />
														<OtherMonthDayStyle ForeColor="#808080" />
														<NextPrevStyle VerticalAlign="Bottom" />
														<DayHeaderStyle BackColor="#CCCCCC" Font-Bold="True" Font-Size="7pt" />
														<TitleStyle BackColor="#999999" BorderColor="Black" Font-Bold="True" />
													</asp:Calendar>
												</td>
											</tr>
											<tr>
												<td>
													<button id="btnReservYes" runat="server" style="width: 75px;" onserverclick="btnReservYes_Click">
														<span><em>Да</em></span></button>
												</td>
												<td>
													<button id="btnReservNo" runat="server" style="width: 75px;" onserverclick="btnReservNo_Click">
														<span><em>Нет</em></span></button>
												</td>
											</tr>
										</table>
									</center>
									<div class="clear"></div>
								</div>
							</div>
							<div class="Widget_Body_bottom"><span></span></div>
						</div>
					</center>
				</div>
			</div>
		</ContentTemplate>
	</asp:UpdatePanel>
</asp:Content>
