<%@ Page Title="" Language="C#" MasterPageFile="~/App_Master/AdminMaster.master"
	AutoEventWireup="true" CodeBehind="Admin.aspx.cs" Inherits="SSManagment.Admin" %>

<asp:Content ID="Content1" ContentPlaceHolderID="cphAdminMenu" runat="server">
	<div>
		<asp:HyperLink ID="HyperLink1" runat="server" NavigateUrl="Seller.aspx">Вернуться к продажам</asp:HyperLink>
		<br />
		<asp:Button ID="btnShowGroups" runat="server" Text="Отобразить Группы" UseSubmitBehavior="False"
			OnClick="btnShowGroups_Click" />
		<br />
		<asp:Button ID="btnShowItems" runat="server" Text="Отобразить Товары" UseSubmitBehavior="False"
			OnClick="btnShowItems_Click" />
		<br />
	</div>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="cphAdminObject" runat="server">
	<div>
		<table runat="server" id="tblGroup" visible="false">
			<tr>
				<td>
					<asp:ListBox ID="lstGroup" runat="server" Height="300px" Width="300px" OnSelectedIndexChanged="lstGroup_SelectedIndexChanged"
						AutoPostBack="True"></asp:ListBox>
				</td>
				<td>
					<asp:ListBox ID="lstSubGroup" runat="server" Height="300px" Width="300px" TabIndex="40">
					</asp:ListBox>
				</td>
			</tr>
			<tr>
				<td>
					<asp:TextBox ID="txtGroupName" runat="server" TabIndex="1"></asp:TextBox>
					<asp:Button ID="btnUpdateGroup" runat="server" Text="Изменить" TabIndex="2" UseSubmitBehavior="False"
						OnClick="btnUpdateGroup_Click" />
					<br />
					<asp:Button ID="btnAddGroup" runat="server" Text="Добавить" OnClick="btnAddGroup_Click"
						TabIndex="2" UseSubmitBehavior="False" />
					<asp:Button ID="btnDelGroup" runat="server" Text="Удалить" OnClick="btnDelGroup_Click"
						TabIndex="3" UseSubmitBehavior="False" />
					<br />
					<asp:Button ID="btnAttachTo" runat="server" Text="Привязать к" TabIndex="3" UseSubmitBehavior="False"
						OnClick="btnAttachTo_Click" />
					<asp:DropDownList ID="ddlAttachTo" runat="server" Width="200px">
					</asp:DropDownList>
				</td>
				<td>
					<asp:TextBox ID="txtSubGroupName" runat="server" TabIndex="44"></asp:TextBox>
					<asp:Button ID="btnUpdateSubGroup" runat="server" Text="Изменить" TabIndex="45" UseSubmitBehavior="False"
						OnClick="btnUpdateSubGroup_Click" />
					<br />
					<asp:Button ID="btnAddSubGroup" runat="server" Text="Добавить" OnClick="btnAddSubGroup_Click"
						TabIndex="46" UseSubmitBehavior="False" />
					<asp:Button ID="btnDellSubGroup" runat="server" Text="Удалить" OnClick="btnDellSubGroup_Click"
						TabIndex="47" UseSubmitBehavior="False" />
					<asp:Button ID="btnMoveToGroup" runat="server" Text="Отвязать" TabIndex="48" UseSubmitBehavior="False"
						OnClick="btnMoveToGroup_Click" />
				</td>
			</tr>
		</table>
		<table runat="server" id="tblItems">
			<tr>
				<td rowspan="3">
					<asp:TreeView ID="treeCategories" runat="server" ExpandDepth="1" AutoGenerateDataBindings="true"
						ForeColor="#333333" ShowLines="True" Height="100%" Width="200px" BackColor="#F7F7DE"
						OnSelectedNodeChanged="treeCategories_SelectedNodeChanged">
						<ParentNodeStyle ForeColor="White" BackColor="#6B696B" BorderColor="#FF6600" BorderStyle="Dashed"
							BorderWidth="1px" Font-Bold="True" NodeSpacing="1px" />
						<RootNodeStyle ForeColor="White" BackColor="#6B696B" BorderColor="#FF6600" BorderWidth="1px"
							Font-Bold="True" NodeSpacing="1px" />
					</asp:TreeView>
				</td>
				<td valign="top">
					<asp:ListBox ID="lstItems" runat="server" Height="300px" Width="300px" AutoPostBack="true"
						OnSelectedIndexChanged="lstItems_SelectedIndexChanged"></asp:ListBox>
				</td>
			</tr>
			<tr>
				<td valign="top">
					<asp:Button ID="Button1" runat="server" Text="Изменить" TabIndex="31" UseSubmitBehavior="False" />
					<asp:Button ID="Button2" runat="server" Text="Снять с продажи" TabIndex="33" UseSubmitBehavior="False" />
					<asp:Button ID="Button3" runat="server" Text="Добавить" TabIndex="35" UseSubmitBehavior="False" />
				</td>
			</tr>
			<tr>
			<td>
			Название: 
				<asp:TextBox ID="txtItemName" runat="server"></asp:TextBox><br />
			Колличество: 
				<asp:TextBox ID="txtItemCount" runat="server"></asp:TextBox><br />
			Измеряется в: 
				<asp:TextBox ID="txtItemMeasure" runat="server"></asp:TextBox><br />
			Цена поставки: 
				<asp:TextBox ID="txtItemAdminPrice" runat="server"></asp:TextBox><br />
			Процент: 
				<asp:TextBox ID="txtItemPct" runat="server"></asp:TextBox><br />
			Мин. колличество для заказа: 
				<asp:TextBox ID="txtItemOrderCount" runat="server"></asp:TextBox><br />
			Разрешать возврат: 
				<asp:CheckBox ID="chbItemCanGiveBack" runat="server" /><br />
			Доступен: 
				<asp:CheckBox ID="chbItemIsActive" runat="server" />
			</td>
			</tr>
		</table>
	</div>
</asp:Content>
