<%@ Page Title="" Language="C#" MasterPageFile="~/App_Master/SellerMaster.master"
	AutoEventWireup="true" CodeBehind="Seller.aspx.cs" Inherits="SSManagment.Seller" %>

<asp:Content ID="cntCategories" ContentPlaceHolderID="cphStandartCategories" runat="server">
	<table cellpadding="0" cellspacing="0">
		<tr>
			<td>
				<div class="Widget_heading_container">
					<span class="Widget_heading_container_Span"></span>
					<h2>
						Разделы</h2>
				</div>
				<div class="Widget_Body_container">
					<div class="Widget_Body_top">
						<span></span>
					</div>
					<div class="Widget_Body_content">
						<div class="clear">
						</div>
						<div style="overflow: auto; width: 200px; background-color: #F7F7DE;">
							<asp:UpdatePanel ID="uplTree" runat="server" UpdateMode="Conditional">
								<ContentTemplate>
									<asp:TreeView ID="treeCategories" runat="server" ExpandDepth="1" AutoGenerateDataBindings="true"
										ForeColor="#333333" ShowLines="True" Height="100%" Width="200px" BackColor="#F7F7DE"
										OnSelectedNodeChanged="treeCategories_SelectedNodeChanged">
										<ParentNodeStyle ForeColor="White" BackColor="#6B696B" BorderColor="#FF6600" BorderStyle="Dashed"
											BorderWidth="1px" Font-Bold="True" NodeSpacing="1px" />
										<RootNodeStyle ForeColor="White" BackColor="#6B696B" BorderColor="#FF6600" BorderWidth="1px"
											Font-Bold="True" NodeSpacing="1px" />
									</asp:TreeView>
								</ContentTemplate>
								<Triggers>
									<asp:AsyncPostBackTrigger ControlID="treeCategories" EventName="DataBinding" />
								</Triggers>
							</asp:UpdatePanel>
						</div>
						<div class="clear">
						</div>
					</div>
				</div>
				<div class="Widget_Body_bottom">
					<span></span>
				</div>
			</td>
		</tr>
	</table>
</asp:Content>
<asp:Content ID="cntProducts" ContentPlaceHolderID="cphStandartProducts" runat="server">
	<asp:UpdatePanel ID="uplProductsGrid" runat="server" UpdateMode="Always">
		<ContentTemplate>
			<div class="Widget_heading_container">
				<span class="Widget_heading_container_Span"></span>
				<h2>
					Товары</h2>
			</div>
			<div class="Widget_Body_container">
				<div class="Widget_Body_top">
					<span></span>
				</div>
				<div class="Widget_Body_content">
					<div class="clear">
					</div>
					<table width="100%">
						<tr>
							<td align="center">
								<table>
									<tr>
										<td align="right">
											<asp:TextBox ID="txtFind" runat="server" Width="200px"></asp:TextBox>
										</td>
										<td>
											<button id="btnFind" runat="server">
												<span><em>Найти</em></span></button>
										</td>
									</tr>
								</table>
							</td>
						</tr>
						<tr>
							<td>
								<asp:GridView ID="gvwProducts" runat="server" AutoGenerateColumns="False" BackColor="White"
									BorderColor="#DEDFDE" BorderStyle="None" CaptionAlign="Top" CellPadding="2" ForeColor="Black"
									GridLines="Vertical" OnRowCommand="gvwProducts_RowCommand" Width="485px" AllowPaging="False"
									Font-Size="8pt">
									<RowStyle BackColor="#F7F7DE" />
									<Columns>
										<asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" Visible="False" />
										<asp:BoundField DataField="name" HeaderText="Название" ReadOnly="True" />
										<asp:BoundField DataField="count" HeaderText="В наличии" NullDisplayText="нет">
											<ControlStyle Width="50px" />
										</asp:BoundField>
										<asp:BoundField DataField="measure" HeaderText="Измерение" NullDisplayText="шт">
											<ControlStyle Width="50px" />
										</asp:BoundField>
										<asp:BoundField DataField="bprice" HeaderText="Цена" NullDisplayText="уточнить">
											<ControlStyle Width="50px" />
										</asp:BoundField>
										<asp:BoundField DataField="reserveCount" HeaderText="Резерв">
											<ControlStyle Width="70px" />
										</asp:BoundField>
										<asp:TemplateField HeaderText="Кол-во">
											<ItemTemplate>
												<asp:TextBox ID="txtBuyCount" runat="server"></asp:TextBox>
											</ItemTemplate>
											<ControlStyle Width="50px" />
										</asp:TemplateField>
										<asp:TemplateField ShowHeader="False">
											<ItemTemplate>
												<asp:ImageButton ID="ibtnAdd" runat="server" CausesValidation="false" CommandName="add"
													ToolTip="Добаваить в корзину" ImageUrl="~/App_Themes/Main/Icons/162px-Ambox_emblem_plus.svg.png"
													CommandArgument='<%# Eval("id") %>' />
											</ItemTemplate>
											<ControlStyle Height="24px" Width="24px" />
										</asp:TemplateField>
										<asp:TemplateField ShowHeader="False">
											<ItemTemplate>
												<asp:ImageButton ID="ibtnSale" runat="server" CausesValidation="false" CommandName="sale"
													CommandArgument='<%# Eval("id") %>' ImageUrl="~/App_Themes/Main/Icons/120px-Emblem-advertisement-dollar.svg.png"
													ToolTip="Продать" />
											</ItemTemplate>
											<ControlStyle Height="24px" Width="24px" />
										</asp:TemplateField>
										<asp:TemplateField ShowHeader="False">
											<ItemTemplate>
												<asp:ImageButton ID="ibtnReserv" runat="server" CausesValidation="false" CommandName="reserved"
													CommandArgument='<%# Eval("id") %>' ImageUrl="~/App_Themes/Main/Icons/48px-Emblem-symbolic-link.svg.png"
													ToolTip="Зарезервировать" />
											</ItemTemplate>
											<ControlStyle Height="24px" Width="24px" />
										</asp:TemplateField>
									</Columns>
									<EmptyDataTemplate>
										<center>
											<span>В выбраном вами разделе продуктов ненайдено!</span></center>
									</EmptyDataTemplate>
									<FooterStyle BackColor="#CCCC99" />
									<PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
									<SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
									<HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
									<AlternatingRowStyle BackColor="White" />
								</asp:GridView>
								&nbsp;
							</td>
						</tr>
					</table>
					<div class="clear">
					</div>
				</div>
			</div>
			<div class="Widget_Body_bottom">
				<span></span>
			</div>
		</ContentTemplate>
	</asp:UpdatePanel>
</asp:Content>
<asp:Content ID="cntBuy" ContentPlaceHolderID="cphStandartBuy" runat="server">
	<asp:UpdatePanel ID="uplShoppingCart" runat="server">
		<ContentTemplate>
			<table cellpadding="0" cellspacing="0">
				<tr>
					<td>
						<div class="Widget_heading_container">
							<span class="Widget_heading_container_Span"></span>
							<h2>
								Список покупок ( корзина)</h2>
						</div>
						<div class="Widget_Body_container">
							<div class="Widget_Body_top">
								<span></span>
							</div>
							<div class="Widget_Body_content">
								<div class="clear">
								</div>
								<table cellpadding="0" cellspacing="0" width="100%">
									<tr>
										<td align="center">
											<asp:GridView ID="gvwShoppingCart" runat="server" Width="100%" AutoGenerateColumns="False"
												BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" CellPadding="2" ForeColor="Black"
												GridLines="Vertical" OnRowCommand="gvwShoppingCart_RowCommand" OnRowDeleting="gvwShoppingCart_RowDeleting"
												Font-Size="8pt">
												<RowStyle BackColor="#F7F7DE" />
												<Columns>
													<asp:BoundField HeaderText="Товар" DataField="name">
														<ControlStyle Width="150px" />
													</asp:BoundField>
													<asp:BoundField HeaderText="Цена" DataField="bprice" NullDisplayText="уточнить">
														<ControlStyle Width="50px" />
													</asp:BoundField>
													<asp:TemplateField HeaderText="Кол-во">
														<ItemTemplate>
															<asp:TextBox ID="txtBuyCount" runat="server" Text='<%# Eval("BuyCount") %>'></asp:TextBox>
														</ItemTemplate>
														<ControlStyle Width="50px" />
													</asp:TemplateField>
													<asp:TemplateField ShowHeader="False">
														<ItemTemplate>
															<asp:ImageButton ID="btnDelete" runat="server" CausesValidation="false" CommandName="delete"
																CommandArgument='<%# Eval("id") %>' ImageUrl="~/App_Themes/Main/Icons/120px-Dialog-error.svg.png"
																ToolTip="Удалить" />
														</ItemTemplate>
														<ControlStyle Height="24px" Width="24px" />
													</asp:TemplateField>
												</Columns>
												<EmptyDataTemplate>
													<center>
														<span>Список покупок пуст</span></center>
												</EmptyDataTemplate>
												<FooterStyle BackColor="#CCCC99" />
												<PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
												<SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
												<HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
												<AlternatingRowStyle BackColor="White" />
											</asp:GridView>
										</td>
									</tr>
									<tr>
										<td>
											<table>
												<tr>
													<td align="left" style="width: 90px">
														<span>Покупатель :</span>
													</td>
													<td align="left">
														<asp:DropDownList ID="drpBuyer" runat="server" Width="120px" AutoPostBack="True">
														</asp:DropDownList>
													</td>
												</tr>
											</table>
										</td>
									</tr>
									<tr>
										<td>
											&nbsp; <span>Итого :</span><asp:Label ID="lblSum" runat="server"></asp:Label>
										</td>
									</tr>
									<tr>
										<td>
											<button id="btnBuy" runat="server" style="width: 100%" onserverclick="btnBuy_Click">
												<span><em>Оформить покупку</em></span></button>
										</td>
									</tr>
								</table>
								<div class="clear">
								</div>
							</div>
						</div>
						<div class="Widget_Body_bottom">
							<span></span>
						</div>
					</td>
				</tr>
				<tr>
					<td>
						<div class="Widget_heading_container">
							<span class="Widget_heading_container_Span"></span>
							<h2>
								Дополнительно</h2>
						</div>
						<div class="Widget_Body_container">
							<div class="Widget_Body_top">
								<span></span>
							</div>
							<div class="Widget_Body_content">
								<div class="clear">
								</div>
								<center>
									<button id="btnAdmin" runat="server" style="width: 180px" onserverclick="btnAdminClick">
										<span><em>Администрирование</em></span></button>
									<br />
									<button id="btnReturn" runat="server" style="width: 180px">
										<span><em>Возврат товара</em></span></button>
								</center>
								<div class="clear">
								</div>
							</div>
						</div>
						<div class="Widget_Body_bottom">
							<span></span>
						</div>
					</td>
				</tr>
			</table>
			<div id="modalBuyConfirm" runat="server" visible="false">
				<div class="overlay">
				</div>
				<div style="top: 48%; position: absolute; left: 48%;">
					<center>
						<div style="width: 180px;">
							<div class="Widget_heading_container">
								<span class="Widget_heading_container_Span"></span>
								<center>
									<h2>
										Оформить покупку?
									</h2>
								</center>
							</div>
							<div class="Widget_Body_container">
								<div class="Widget_Body_top">
									<span></span>
								</div>
								<div class="Widget_Body_content">
									<div class="clear">
									</div>
									<center>
										<table>
											<tr>
												<td>
													<button id="btnYes" runat="server" style="width: 75px;" onserverclick="btnYes_Click">
														<span><em>Да</em></span></button>
												</td>
												<td>
													<button id="btnCancel" runat="server" style="width: 75px;" onserverclick="btnCancel_Click">
														<span><em>Нет</em></span></button>
												</td>
											</tr>
										</table>
									</center>
									<div class="clear">
									</div>
								</div>
							</div>
							<div class="Widget_Body_bottom">
								<span></span>
							</div>
						</div>
					</center>
				</div>
			</div>
			<div id="modalReserv" runat="server" visible="false">
				<div class="overlay">
				</div>
				<div style="top: 45%; position: absolute; left: 40%;">
					<center>
						<div style="width: 400px;">
							<div class="Widget_heading_container">
								<span class="Widget_heading_container_Span"></span>
								<center>
									<h2>
										Зарезервировать товар
									</h2>
								</center>
							</div>
							<div class="Widget_Body_container">
								<div class="Widget_Body_top">
									<span></span>
								</div>
								<div class="Widget_Body_content">
									<div class="clear">
									</div>
									<center>
										<table width="100%">
											<tr>
												<td colspan="2">
													<table cellpadding="0" width="100%">
														<tr>
															<td align="right">
																<span>Название товара :</span>
															</td>
															<td align="left">
																<asp:Label ID="lblResrvName" runat="server"></asp:Label>
																<asp:HiddenField ID="hdnResrvID" runat="server" />
															</td>
														</tr>
														<tr>
															<td align="right">
																<span>В наличии :</span>
															</td>
															<td align="left">
																<asp:Label ID="lblResrvCount" runat="server"></asp:Label>
															</td>
														</tr>
														<tr>
															<td align="right">
																<span>Зарезервировано :</span>
															</td>
															<td align="left">
																<asp:Label ID="lblResrvReserved" runat="server"></asp:Label>
															</td>
														</tr>
														<tr>
															<td align="right">
																<span>Цена :</span>
															</td>
															<td align="left">
																<asp:Label ID="lblResrvBprice" runat="server"></asp:Label>
															</td>
														</tr>
														<tr>
															<td align="right">
																<span>Зарезервировать :</span>
															</td>
															<td align="left">
																<asp:TextBox ID="txtResrvBuyCount" runat="server" OnTextChanged="txtResrvBuyCount_TextChanged"></asp:TextBox>
															</td>
														</tr>
														<tr>
															<td align="right">
																<span>Итого :</span>
															</td>
															<td align="left">
																<asp:Label ID="lblResrvSum" runat="server"></asp:Label>
															</td>
														</tr>
													</table>
												</td>
											</tr>
											<tr>
												<td colspan="2" align="center">
													<span>Непродавать товар до</span>
													<asp:Calendar ID="calResrvReservDateTo" runat="server" BackColor="White" BorderColor="#999999"
														CellPadding="4" DayNameFormat="Shortest" Font-Names="Verdana" Font-Size="8pt"
														ForeColor="Black" Height="180px" Width="200px" OnSelectionChanged="calResrvReservDateTo_SelectionChanged">
														<SelectedDayStyle BackColor="#666666" Font-Bold="True" ForeColor="White" />
														<SelectorStyle BackColor="#CCCCCC" />
														<WeekendDayStyle BackColor="#FFFFCC" />
														<TodayDayStyle BackColor="#CCCCCC" ForeColor="Black" />
														<OtherMonthDayStyle ForeColor="#808080" />
														<NextPrevStyle VerticalAlign="Bottom" />
														<DayHeaderStyle BackColor="#CCCCCC" Font-Bold="True" Font-Size="7pt" />
														<TitleStyle BackColor="#999999" BorderColor="Black" Font-Bold="True" />
													</asp:Calendar>
												</td>
											</tr>
											<tr>
												<td>
													<button id="btnReservYes" runat="server" style="width: 75px;" onserverclick="btnReservYes_Click">
														<span><em>Да</em></span></button>
												</td>
												<td>
													<button id="btnReservNo" runat="server" style="width: 75px;" onserverclick="btnReservNo_Click">
														<span><em>Нет</em></span></button>
												</td>
											</tr>
										</table>
									</center>
									<div class="clear">
									</div>
								</div>
							</div>
							<div class="Widget_Body_bottom">
								<span></span>
							</div>
						</div>
					</center>
				</div>
			</div>
		</ContentTemplate>
	</asp:UpdatePanel>
</asp:Content>
