<?xml version="1.0" encoding="utf-8"?>
<Database Name="SM" Class="ssmDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SUZEV-A\SQLEXPRESS;Initial Catalog=SM;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.buyer" Member="buyers">
    <Type Name="buyer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="pct" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="isActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="buyer_logSale" Member="logSales" ThisKey="id" OtherKey="buyerId" Type="logSale" />
      <Association Name="buyer_logActivity" Member="logActivities" ThisKey="id" OtherKey="buyerId" Type="logActivity" />
    </Type>
  </Table>
  <Table Name="dbo.seller" Member="sellers">
    <Type Name="seller">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fullName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="isAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="login" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="isActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="seller_logSale" Member="logSales" ThisKey="id" OtherKey="sellerId" Type="logSale" />
    </Type>
  </Table>
  <Table Name="dbo.[group]" Member="groups">
    <Type Name="group">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="parent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="group_group" Member="groups" ThisKey="id" OtherKey="parent" Type="group" />
      <Association Name="group_item" Member="items" ThisKey="id" OtherKey="groupId" Type="item" />
      <Association Name="group_group" Member="group1" ThisKey="parent" OtherKey="id" Type="group" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.item" Member="items">
    <Type Name="item">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="groupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="measure" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pct" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="adminPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="reserveCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="reserveEndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[order]" Member="order" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="countToOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="canGiveBack" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="item_logSale" Member="logSales" ThisKey="id" OtherKey="itemId" Type="logSale" />
      <Association Name="group_item" Member="group" ThisKey="groupId" OtherKey="id" Type="group" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.logActivity" Member="logActivities">
    <Type Name="logActivity">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="action" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="buyerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="informAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="buyer_logActivity" Member="buyer" ThisKey="buyerId" OtherKey="id" Type="buyer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.logSales" Member="logSales">
    <Type Name="logSale">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="itemId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="itemsCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="buyerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sellerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="isGiveBack" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="item_logSale" Member="item" ThisKey="itemId" OtherKey="id" Type="item" IsForeignKey="true" />
      <Association Name="seller_logSale" Member="seller" ThisKey="sellerId" OtherKey="id" Type="seller" IsForeignKey="true" />
      <Association Name="buyer_logSale" Member="buyer" ThisKey="buyerId" OtherKey="id" Type="buyer" IsForeignKey="true" />
    </Type>
  </Table>
</Database>